/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : bigint,
}
export interface MembershipTier {
  'id' : bigint,
  'displayOrder' : bigint,
  'name' : string,
  'benefits' : Array<string>,
  'price' : string,
}
export interface StaffMember {
  'id' : bigint,
  'bio' : string,
  'displayOrder' : bigint,
  'name' : string,
  'role' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], bigint>,
  'createMembershipTier' : ActorMethod<
    [string, string, Array<string>, bigint],
    bigint
  >,
  'createStaffMember' : ActorMethod<[string, string, string, bigint], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteMembershipTier' : ActorMethod<[bigint], undefined>,
  'deleteStaffMember' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllContent' : ActorMethod<[], Array<[string, string]>>,
  'getAllMembershipTiers' : ActorMethod<[], Array<MembershipTier>>,
  'getAllStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentByKey' : ActorMethod<[string], string>,
  'getMembershipTier' : ActorMethod<[bigint], MembershipTier>,
  'getPublishedAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getStaffMember' : ActorMethod<[bigint], StaffMember>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initDefaultContent' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnnouncementPublished' : ActorMethod<[bigint, boolean], undefined>,
  'setContentByKey' : ActorMethod<[string, string], undefined>,
  'updateAnnouncement' : ActorMethod<[bigint, string, string], undefined>,
  'updateMembershipTier' : ActorMethod<
    [bigint, string, string, Array<string>, bigint],
    undefined
  >,
  'updateStaffMember' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];