/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLogEntry {
  'id' : string,
  'action' : string,
  'adminName' : string,
  'timestamp' : bigint,
  'details' : string,
  'principalText' : string,
}
export interface AdminEntry {
  'principal' : Principal,
  'isSuperAdmin' : boolean,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : bigint,
}
export interface Booking {
  'id' : string,
  'status' : string,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'notes' : string,
  'timeSlot' : string,
  'courtType' : string,
}
export interface Enquiry {
  'id' : string,
  'status' : string,
  'tierId' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface GalleryImage {
  'id' : string,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'storageKey' : string,
  'altText' : string,
}
export interface MembershipTier {
  'id' : bigint,
  'displayOrder' : bigint,
  'name' : string,
  'benefits' : Array<string>,
  'price' : string,
}
export interface StaffMember {
  'id' : bigint,
  'bio' : string,
  'displayOrder' : bigint,
  'name' : string,
  'role' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<
    [string, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCallerUserRoleWithSuperAdminCheck' : ActorMethod<
    [Principal, UserRole],
    undefined
  >,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createAnnouncement' : ActorMethod<[string, string], bigint>,
  'createMembershipTier' : ActorMethod<
    [string, string, Array<string>, bigint],
    bigint
  >,
  'createStaffMember' : ActorMethod<[string, string, string, bigint], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteGalleryImage' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteMembershipTier' : ActorMethod<[bigint], undefined>,
  'deleteStaffMember' : ActorMethod<[bigint], undefined>,
  'getActivityLog' : ActorMethod<[bigint], Array<ActivityLogEntry>>,
  'getAllAdmins' : ActorMethod<[], Array<AdminEntry>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContent' : ActorMethod<[], Array<[string, string]>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllMembershipTiers' : ActorMethod<[], Array<MembershipTier>>,
  'getAllStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentByKey' : ActorMethod<[string], string>,
  'getMembershipTier' : ActorMethod<[bigint], MembershipTier>,
  'getPublishedAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getStaffMember' : ActorMethod<[bigint], StaffMember>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'initDefaultContent' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerSuperAdmin' : ActorMethod<[], boolean>,
  'reorderGalleryImages' : ActorMethod<
    [Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnnouncementPublished' : ActorMethod<[bigint, boolean], undefined>,
  'setContentByKey' : ActorMethod<[string, string], undefined>,
  'setSuperAdmin' : ActorMethod<[Principal, boolean], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateAnnouncement' : ActorMethod<[bigint, string, string], undefined>,
  'updateBookingStatus' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateEnquiryStatus' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateGalleryImage' : ActorMethod<
    [string, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateMembershipTier' : ActorMethod<
    [bigint, string, string, Array<string>, bigint],
    undefined
  >,
  'updateStaffMember' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];