/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
});
export const MembershipTier = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createMembershipTier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createStaffMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteMembershipTier' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
  'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentByKey' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMembershipTier' : IDL.Func([IDL.Nat], [MembershipTier], ['query']),
  'getPublishedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getStaffMember' : IDL.Func([IDL.Nat], [StaffMember], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'initDefaultContent' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnnouncementPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setContentByKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateMembershipTier' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'updateStaffMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
  });
  const MembershipTier = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createMembershipTier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createStaffMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteMembershipTier' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllMembershipTiers' : IDL.Func(
        [],
        [IDL.Vec(MembershipTier)],
        ['query'],
      ),
    'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentByKey' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMembershipTier' : IDL.Func([IDL.Nat], [MembershipTier], ['query']),
    'getPublishedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getStaffMember' : IDL.Func([IDL.Nat], [StaffMember], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'initDefaultContent' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnnouncementPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setContentByKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateMembershipTier' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'updateStaffMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };