/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityLogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'adminName' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'principalText' : IDL.Text,
});
export const AdminEntry = IDL.Record({
  'principal' : IDL.Principal,
  'isSuperAdmin' : IDL.Bool,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'timeSlot' : IDL.Text,
  'courtType' : IDL.Text,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'tierId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'storageKey' : IDL.Text,
  'altText' : IDL.Text,
});
export const MembershipTier = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCallerUserRoleWithSuperAdminCheck' : IDL.Func(
      [IDL.Principal, UserRole],
      [],
      [],
    ),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createMembershipTier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createStaffMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryImage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteMembershipTier' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
  'getActivityLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityLogEntry)],
      ['query'],
    ),
  'getAllAdmins' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
  'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentByKey' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMembershipTier' : IDL.Func([IDL.Nat], [MembershipTier], ['query']),
  'getPublishedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getStaffMember' : IDL.Func([IDL.Nat], [StaffMember], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'initDefaultContent' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderGalleryImages' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnnouncementPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setContentByKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setSuperAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateEnquiryStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateMembershipTier' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'updateStaffMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityLogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'adminName' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'principalText' : IDL.Text,
  });
  const AdminEntry = IDL.Record({
    'principal' : IDL.Principal,
    'isSuperAdmin' : IDL.Bool,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'timeSlot' : IDL.Text,
    'courtType' : IDL.Text,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'tierId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'storageKey' : IDL.Text,
    'altText' : IDL.Text,
  });
  const MembershipTier = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCallerUserRoleWithSuperAdminCheck' : IDL.Func(
        [IDL.Principal, UserRole],
        [],
        [],
      ),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createMembershipTier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createStaffMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryImage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteMembershipTier' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
    'getActivityLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityLogEntry)],
        ['query'],
      ),
    'getAllAdmins' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllMembershipTiers' : IDL.Func(
        [],
        [IDL.Vec(MembershipTier)],
        ['query'],
      ),
    'getAllStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentByKey' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMembershipTier' : IDL.Func([IDL.Nat], [MembershipTier], ['query']),
    'getPublishedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getStaffMember' : IDL.Func([IDL.Nat], [StaffMember], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'initDefaultContent' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderGalleryImages' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnnouncementPublished' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setContentByKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setSuperAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateEnquiryStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateMembershipTier' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'updateStaffMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };